version: "3"

services:
  network-discovery:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        GROUPID: 20001
        http_proxy: ${http_proxy:-}
        https_proxy: ${https_proxy:-}
    image: mwallraf/nmap-network-discovery:1.1
    # command: bash...
    # volumes:
    #   -
    # environment:
    #   - OUTPUTFOLDER=another_value
